# Generated by Django 4.0.4 on 2022-05-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='birth date'),
        ),
    ]
